### ISSUE TITLE
python-glanceclient code does not actually work

### ISSUE THREAD

**Issue by zaneb** [sdake/heat-jeos#35]
The commit 39401324d5114a99d697f55da5255c6df7027c43 introduces support for the python-glanceclient package that shipped in the Folsom timeframe, if it is present. However, when python-glanceclient is installed, I cannot actually use glance:

```
ERROR:Request returned failure status.
An existing JEOS was found on disk. Do you want to build a fresh JEOS? (y/n) n
ERROR:Request returned failure status.
ERROR: Failed to add image. Got error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/heat_jeos-7-py2.7.egg/EGG-INFO/scripts/heat-jeos", line 157, in command_create
    image = glance.find_image_by_name(client, image_name)
  File "/usr/lib/python2.7/site-packages/heat_jeos-7-py2.7.egg/heat_jeos/glance_clients.py", line 100, in find_image_folsom
    return images.next()
  File "/usr/lib/python2.7/site-packages/python_glanceclient-0.6.0-py2.7.egg/glanceclient/v1/images.py", line 130, in paginate
    images = self._list(url, "images")
  File "/usr/lib/python2.7/site-packages/python_glanceclient-0.6.0-py2.7.egg/glanceclient/common/base.py", line 53, in _list
    resp, body = self.api.json_request('GET', url)
  File "/usr/lib/python2.7/site-packages/python_glanceclient-0.6.0-py2.7.egg/glanceclient/common/http.py", line 196, in json_request
    resp, body_iter = self._http_request(url, method, **kwargs)
  File "/usr/lib/python2.7/site-packages/python_glanceclient-0.6.0-py2.7.egg/glanceclient/common/http.py", line 180, in _http_request
    raise exc.from_response(resp)
HTTPNotFound: HTTPNotFound (HTTP 404)
WARNING:Note: Your image metadata may still be in the registry, but the image's status will likely be 'killed'.
```

**Comment by nakamichi** [comment]
I took in this bugfix and tried heat-jeos again.
Glance registration is good.
